file_path: /media/igor/n1/www/psr3SP/log
log_level_files:
  - EMERGENCY: emergency.log
  - ALERT: alert.log
  - CRITICAL: critical.log
  - ERROR: error.log
  - WARNING: warning.log
  - NOTICE: notice.log
  - INFO: info.log
  - DEBUG: debug.log